#!/bin/bash

DUDE=`ps caux | grep hashcat | awk '{print $1}'`

cat /etc/update-motd.d/hashcat.txt

ps caux | grep hashcat > /dev/null

if [ $? -eq 0 ] ; then
    printf '\n   Hashcat is being used right now by %s\n\n' $DUDE
else
    printf '\n     Hashcat is not running at the moment\n\n'
fi
