#!/bin/bash

cat /etc/update-motd.d/hashcat.txt

ps cax | grep hashcat > /dev/null

if [ $? -eq 0 ] ; then
    printf '\n     Hashcat is running at the moment\n\n'
else
    printf '\n     Hashcat is not running at the moment\n\n'
fi
